FROM alpine AS stage1
LABEL maintainer="Collabnix"
RUN echo "Welcome to Docker Labs!" > /opt/index.html

FROM nginx:alpine
LABEL maintainer="Collabnix"
COPY --from=stage1 /opt/index.html /usr/share/nginx/html/
COPY --from=nginx:latest /etc/nginx/nginx.conf /nginx.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]
